### ISSUE TITLE
Feature request: Add SVG icons of each social network

### ISSUE THREAD

**Issue by ajreading** [castlegateit/cgit-wp-socialize#1]
Every time this plugin is used you'd need to obtain some icons for presentation. Could we add simple SVG icons for each network? If we have icons for the Twitter bird and Facebook "f", then it's a simple case of styling them up as you wish.

**Comment by ajreading** [comment]
It may also be worth adding some base styles for ease of installation. Circular, or square buttons for example.

**Comment by johnkhughes** [comment]
This is now available in the v2 branch, which is in testing.
