### ISSUE TITLE
Warnings using Widget and SVG embedding

### ISSUE THREAD

**Issue by ajreading** [castlegateit/cgit-wp-socialize#2]
When using a Socialize widget on a clean site with SVG embeds turned on, each social buttons produces a warning:

`Warning: file_get_contents(./icons/facebook.svg): failed to open stream: No such file or directory in /path/wp-content/plugins/cgit-wp-socialize/classes/Cgit/Socialize.php on line 325`

**Comment by johnkhughes** [comment]
Looks like this fixed last year.
